### ISSUE TITLE
Why do siamese network tracking algorithms basically not use feature fusion such as FPN?

### ISSUE THREAD

**Issue by BridgeLee** [MegviiDetection/video_analyst#179]
Why do siamese network tracking algorithms basically not use feature fusion such as FPN ? Is it for speed reasons or for other reasons?
Thank you very much.

**Comment by lzx1413** [comment]
Because in the process of cropping search image, We suppose that the target size does not change drastically.  It is based on the smooth of video sequences. Hence the scale is not a concerned problem. Maybe FPN can make the extracted fused feature better for SOT, whose improvement is trivial in our experiments.

**Comment by MARMOTatZJU** [comment]
Issue closed as no longer discussion proceeds. Feel free to reopen it.
