### ISSUE TITLE
超参搜索

### ISSUE THREAD

**Issue by zhu2014yi** [MegviiDetection/video_analyst#19]
请问是否考虑写一个超参搜索函数，类似于pysot里面的hp_search.py

**Comment by MARMOTatZJU** [comment]
@zhu2014yi

Added to our TODO list.

However, we would like to point out that it is not recommended to perform hp_search on __OTB__ or __VOT__ on which some people are prone to do so, based on our observation under the issues of PySOT (e.g. [issue #242](https://github.com/STVIR/pysot/issues/242)). The reason is that they are  _test benchmark_. By definition, Trackers are allowed to fine-tuned hyper-params on val-set, while any information from test-set is forbidden to be accessed before you stop preparing your tracker (including hyper-param fine-tuning).

**Comment by zhu2014yi** [comment]
thanks
