### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by HAoYifei996** [MegviiDetection/video_analyst#41]
Hi I am trying to run DDP training, it seems 4 gpu is not enough for my hardware device. However it seems not working when I set `os.environ[“CUDA_VISIBLE_DEVICES”]=“0,1,2,3,4,5,6,7”` as it’s still training on 4 gpu. I wonder why that might be? Thanks!

**Comment by HAoYifei996** [comment]
Resolved.

**Comment by HAoYifei996** [comment]
Hi, Sorry to reopen it. I have made it train on 8 GPUs (2080Ti), but still, it keeps giving `CUDA out of memory `error. I have tried to lower the minibatch and #workers and it seems not helping. I wonder what could be the problem?

**Comment by MARMOTatZJU** [comment]
@HAoYifei996 Could you please provide the following information so that we can understand your context ?

- experiment configuration file (.yaml)
- batch size inside this .yaml file

BTW,  the master branch has been updated recently. Consider fetching the newest commit and trying again.

**Comment by HAoYifei996** [comment]
I am using `siamfcpp_googlenet-dist_trn.yaml`. Inside, I have changed the `num_process` to 8, batch size to 64 and `# of workers` to 16

**Comment by MARMOTatZJU** [comment]
@HAoYifei996 DDP has bug. We plan to fix it.
However, DP is runnable. Consider switching to DP (experiments/siamfcpp/train/siamfcpp_googlenet-trn.yaml) and see if this error disappears.

**Comment by HAoYifei996** [comment]
Hi，Thanks for the solution. By using DP, does that mean I cannot use multiple GPUs to do the training?






------------------ Original ------------------

**Comment by MARMOTatZJU** [comment]
@HAoYifei996 Consider moving "model.set_device(torch.device(devs[0]))" in _main/dist_train.py_ after the instantiation of _optimizer_ so that the order look like this:
```
# build optimizer
optimizer = optim_builder.build(task, task_cfg.optim, model)
model.set_device(torch.device(devs[0]))
```

This seems to be related to a PyTorch issue. We plan to report this issue to PyTorch.

BTW, DP also uses multi-GPU. The main difference between DP and DDP is that DDP spawns sub-processes under main process and each sub-process is responsible for a portion of batch, while DP host everything with single process. They both exploit multi-GPU.
