### ISSUE TITLE
some question in paper

### ISSUE THREAD

**Issue by buaacarzp** [MegviiDetection/video_analyst#62]
What is the label of the cls branch?  I can't find the defined cls, Is the region of bbox mapped to 1 in the featuremap ?  And how to defined the regession branch label ? 
In the SiamRPN++,I know the label is defined by cal the iou between anchor and gt. but I can't find the anchor free style model that how to define the label .
Give you my best wishes,bro,I wanna to get the answer.

**Comment by MARMOTatZJU** [comment]
@buaacarzp 
- About "Label of the cls branch"
  - a pixel is assigned as positive sample if it falls in the gt box, otherwise negative (the same as [FCOS](https://arxiv.org/abs/1904.01355)),
- About "regression branch label"
  -  firstly, we defined the anchor-free box representation. As it is reversible, we encode the get box into this representation. Also, see [FCOS](https://arxiv.org/abs/1904.01355)) for details.

You can check out the [densebox_target.py](https://github.com/MegviiDetection/video_analyst/blob/master/videoanalyst/data/target/target_impl/densebox_target.py) to find the code and details.

**Comment by MARMOTatZJU** [comment]
Not that theoretically any bbox representation that does not require anchor settings is feasible in our framework. FCOS just provides a tested implementation, while other qualified methods are possible.

**Comment by buaacarzp** [comment]
> Not that theoretically any bbox representation that does not require anchor settings is feasible in our framework. FCOS just provides a tested implementation, while other qualified methods are possible.

thank you bro, I find the label is defined in here:```videoanalyst/data/target/target_impl/utils/make_densebox_target.py```
it return three label :cls_res_final, ctr_res_final, gt_boxes_res_final ,respectively represent cls branch label ,pss branch label, bbox label,  I'll take a moment to look at this.
Last,I want to make sure:
 1.  the label generated here is the same as the FCOS or not.
 2.  I want to try run the make_densebox_target.py , but it tell me I haven't densebox_target function and I don't know where the parameters of config that are passed into this function are introduced.

**Comment by MARMOTatZJU** [comment]
- 1. not guaranteed to be the same as the [latest official version](https://github.com/aim-uofa/adet). Actually, the code was borrowed from an unofficial implementation of FCOS. We plan to replace the current target maker with a neater version.
- 2. There is docstring inside the _make_densebox_target.py_ . Is it unclear for you? Feel free to point it out if it is the case so that we can improve the codebase.

```
    Arguments
    ---------
    gt_boxes : np.array
        ground truth bounding boxes with class, shape=(N, 5), order=(x0, y0, x1, y1, class)
    config: configuration of target making (old format)
        Keys
        ----
        x_size : int
            search image size
        score_size : int
            score feature map size
        total_stride : int
            total stride of backbone
        score_offset : int
            offset between the edge of score map and the border of the search image
```

**Comment by buaacarzp** [comment]
> 1. There is docstring inside the _make_densebox_target.py_ . Is it unclear for you? Feel free to point it out if it is the case so that we can improve the codebase.


Bro，this part of the middle and the following code is really not very well  to read, not only just for me. Hopefully you'll add a description of the steps here in the most recent version.
Before I close this question, I want to say thank you.

**Comment by buaacarzp** [comment]
close issue.
